"""empty message

Revision ID: 11024c27c996
Revises: 83486672ff7e
Create Date: 2023-10-10 15:07:37.144299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11024c27c996'
down_revision = '83486672ff7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
