"""empty message

Revision ID: 9ff77df052be
Revises: 11024c27c996
Create Date: 2023-10-11 10:16:01.663227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff77df052be'
down_revision = '11024c27c996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('rotation_period', sa.Integer(), nullable=True),
    sa.Column('gravity', sa.String(length=50), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('climate', sa.String(length=50), nullable=True),
    sa.Column('terrain', sa.String(length=50), nullable=True),
    sa.Column('surface_water', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('starship_class', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('cost_in_credits', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('consumables', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fav__planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav__starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starship', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['starship'], ['starships.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav__characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('planet', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('starship', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'starships', ['starship'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planet'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('starship')
        batch_op.drop_column('planet')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')

    op.drop_table('fav__characters')
    op.drop_table('fav__starships')
    op.drop_table('fav__planets')
    op.drop_table('starships')
    op.drop_table('planets')
    # ### end Alembic commands ###
